/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Config = t.iface([], {
  "threads": t.opt(t.union("number", t.lit("auto"))),
  "logs": t.opt(t.iface([], {
    "level": t.union(t.lit("debug"), t.lit("warn"), t.lit("error")),
    "path": t.opt("string"),
  })),
  "server": t.iface([], {
    "protocol": t.union(t.lit("http"), t.lit("https"), t.lit("http2")),
    "port": "number",
    "certs": t.opt(t.iface([], {
      "cert": "string",
      "key": "string",
    })),
  }),
  "monitor": t.opt(t.iface([], {
    "enabled": "boolean",
    "interval": t.opt("number"),
    "endpoint": t.opt("string"),
  })),
  "rules": t.array(t.iface([], {
    "method": t.opt(t.union(t.lit("GET"), t.lit("POST"), t.lit("PUT"), t.lit("DELETE"), t.lit("OPTIONS"))),
    "path": "string",
    "dest": "string",
    "destPath": t.opt("string"),
    "headers": t.opt("any"),
    "query": t.opt("any"),
  })),
});

const exportedTypeSuite: t.ITypeSuite = {
  Config,
};
export default exportedTypeSuite;
